# Generated by Django 2.2 on 2020-02-11 11:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('r_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AircraftLoacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapp.Aircraft')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapp.Operator'),
        ),
    ]
